# docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
       - 8081:8080
       - 50000:50000
      links:
       - sonarqube
      container_name: jenkins
      restart: unless-stopped
      volumes:
      - /Users/tadelegan/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    agent: 
#      image: topsinfinite/jenkins-maven-agent:git
      image: tosicky/build-tools:latest
      privileged: true
      user: root
      container_name: jenkins-agent
      links:
       - sonarqube
      expose:
        - 22
      environment: 
       - JENKINS_AGENT_SSH_PUBKEY=<SSH-PUBLIC-KEY>
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    sonarqube:
       container_name: sonarqube01
       image: sonarqube
       depends_on:
          - db
       environment:
         SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
         SONAR_JDBC_USERNAME: sonar
         SONAR_JDBC_PASSWORD: sonar
       volumes:
         - sonarqube-data:/opt/sonarqube/data 
         - sonarqube-extensions:/opt/sonarqube/extensions 
         - sonarqube-logs:/opt/sonarqube/logs sonarqube 
       ports:
         - "9090:9000"

    db:
       image: postgres:12
       ports:
        - "5432:5432"
       environment:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar #tochange
       volumes:
         - postgresql:/var/lib/postgresql
         - postgresql_data:/var/lib/postgresql/data

  volumes:
    sonarqube-data:
      external: true
    sonarqube-extensions:
      external: true
    sonarqube-logs:
      external: true
    postgresql:
     external: true
    postgresql_data:
     external: true
